### ISSUE TITLE
Application health goes "Unknown" time to time showing and error in Application conditions

### ISSUE THREAD

**Issue by ckeragala** [argoproj-labs/applicationset#203] opened 2021-04-16 11:49 UTC
**Describe the bug**
Following error is show in Application conditions section and suddenly disappears. The application state becomes healthy again. This happens time to time.
![image](https://user-images.githubusercontent.com/54570293/115020036-9c28aa00-9ed7-11eb-932c-3e3a08a43d23.png)

```
<string>:6: attempt to index a non-table object(string) with key 'find' stack traceback: <string>:6: in main chunk [G]: ?
```
![image](https://user-images.githubusercontent.com/54570293/115098938-7b506b00-9f50-11eb-8d3e-41d07adc7bd0.png)

**To Reproduce:**
Create an AppSet, I used git-generator-files
Sync the app
See the error

Cannot produce same issue if I directly deploy via ArgoCD `Application`

AppSet version: v1.0.1
ArgoCD version: v2.0.0 / v2.0.1

**Comment by jgwest** [comment] 2021-04-19 16:28
Hi @ckeragala , I'm not able to reproduce using the [git-generator-files-directory](https://github.com/argoproj-labs/applicationset/tree/master/examples/git-generator-files-discovery) example. I create that AppSet, sync it, and don't see an error. Likewise I don't any issues with the events (see screenshot)

Any other information you can provide that would be helpful in reproducing? Would you be able to provide a small test case that reproduces it?

![image](https://user-images.githubusercontent.com/7594762/115270583-72a39480-a10a-11eb-9421-5cc3b423c82d.png)

**Comment by alexmt** [comment] 2021-04-19 16:32
I think this is a duplicate of https://github.com/argoproj/argo-cd/issues/6039 . It is not really related to application set.

**Comment by jgwest** [comment] 2021-04-19 16:58
Aha, thanks for the info @alexmt!

**Comment by ckeragala** [comment] 2021-04-20 12:25
Thanks all, looks like it. This is not related to AppSet, but something to do with `kubernetes-external-secrets` and argocd 2.0 health checks

**Closed** 2021-04-20 13:02 UTC
Labels: bug
